# Generated by Django 5.0.7 on 2024-08-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to='product_info_images/'),
            preserve_default=False,
        ),
    ]
