# Generated by Django 5.0.7 on 2024-08-05 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0002_product_info_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to='product_info_images/'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
