# Generated by Django 5.0.7 on 2024-08-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0003_alter_product_info_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='product_image',
            field=models.ImageField(upload_to='product_info_images/'),
        ),
    ]
