# Generated by Django 5.0.7 on 2024-08-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0006_product_info_inventory_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
